# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barril',
            name='Altura',
            field=models.IntegerField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, null=True),
        ),
        migrations.AlterField(
            model_name='barril',
            name='Diametro',
            field=models.IntegerField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, null=True),
        ),
        migrations.AlterField(
            model_name='barril',
            name='Material',
            field=models.CharField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='malta',
            name='EBC',
            field=models.CharField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='malta',
            name='MC',
            field=models.CharField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=10, null=True),
        ),
    ]
