# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20171002_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado',
            fields=[
                ('insumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.Insumo')),
            ],
            bases=('inventario.insumo',),
        ),
    ]
