# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_fermentador_numero_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barril',
            name='Numero_serie',
        ),
    ]
