# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_auto_20180405_1526'),
        ('inventario', '0005_auto_20180404_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(choices=[('U', 'Unidad'), ('100G', '100 Gramos'), ('1K', '1 Kg'), ('10K', '10 Kg'), ('25K', '25 Kg'), ('1L', '1 Litro'), ('5L', '5 Litros')], default='U', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=20)),
                ('cantidad', models.FloatField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'})),
                ('p_unitario', models.FloatField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'})),
                ('subtotal', models.FloatField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'})),
                ('compra', models.ForeignKey(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Compra')),
                ('insumo', models.ForeignKey(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, related_name='add_insumo', to='inventario.Insumo')),
            ],
        ),
        migrations.AddField(
            model_name='barril',
            name='compra',
            field=models.ForeignKey(default=1, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Compra'),
        ),
    ]
