# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_fermentador_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='barril',
            name='Carbonatado',
            field=models.BooleanField(default=False, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AlterField(
            model_name='barril',
            name='Ubicacion',
            field=models.CharField(default='Ke\xf1ua', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100),
        ),
    ]
