# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20170922_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botella',
            name='Litros',
            field=models.FloatField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
    ]
