# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_botella_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='barril',
            name='p_unitario',
            field=models.FloatField(default=1, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AddField(
            model_name='botella',
            name='p_unitario',
            field=models.FloatField(default=1, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AddField(
            model_name='fermentador',
            name='p_unitario',
            field=models.FloatField(default=1, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
    ]
