# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20170922_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botella',
            name='Llenas',
            field=models.IntegerField(default=0, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
    ]
