# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Representante', models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Telefono', models.IntegerField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Direccion', models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Email', models.EmailField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Representante', models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Rubro', models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Telefono', models.IntegerField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Direccion', models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Email', models.EmailField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
            ],
        ),
    ]
