# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Direccion',
            field=models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Representante',
            field=models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100, null=True),
        ),
    ]
