# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_auto_20171002_1643'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_compra', models.DateField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, verbose_name=b'Fecha de Compra')),
                ('Fecha_entrega', models.DateField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, verbose_name=b'Fecha de Entrega')),
                ('Factura', models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100, null=True)),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Precio_unidad', models.FloatField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Precio_total', models.FloatField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Observaciones', models.TextField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=300, null=True)),
                ('Comprador', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Producto', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Insumo')),
                ('Proveedor', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Proveedor')),
                ('Unidad_de_medida', models.ForeignKey(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Unidad_medida')),
            ],
        ),
    ]
