# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Cantidad',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Comprador',
            field=models.ForeignKey(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Factura',
            field=models.CharField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Fecha_compra',
            field=models.DateField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Fecha_entrega',
            field=models.DateField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Observaciones',
            field=models.TextField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Precio_total',
            field=models.FloatField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Precio_unidad',
            field=models.FloatField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Producto',
            field=models.ForeignKey(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Insumo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Proveedor',
            field=models.ForeignKey(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Unidad_de_medida',
            field=models.ForeignKey(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Unidad_medida'),
        ),
    ]
