# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20180404_1245'),
        ('contabilidad', '0003_compraitem_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraBarril',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(choices=[(b'U', b'Unidad'), (b'1K', b'1 Kg'), (b'10K', b'10 Kg'), (b'25K', b'25 Kg'), (b'1L', b'1 Litro'), (b'5L', b'5 Litros')], default=b'U', error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=20)),
                ('cantidad', models.FloatField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('p_unitario', models.FloatField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('subtotal', models.FloatField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('barril', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, related_name='add_insumo', to='inventario.Barril')),
                ('compra', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Compra')),
            ],
        ),
        migrations.RenameModel(
            old_name='CompraItem',
            new_name='CompraInsumo',
        ),
    ]
