# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_auto_20180405_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprabarril',
            name='presentacion',
            field=models.CharField(choices=[(b'U', b'Unidad'), (b'100G', b'100 Gramos'), (b'1K', b'1 Kg'), (b'10K', b'10 Kg'), (b'25K', b'25 Kg'), (b'1L', b'1 Litro'), (b'5L', b'5 Litros')], default=b'U', error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='comprainsumo',
            name='presentacion',
            field=models.CharField(choices=[(b'U', b'Unidad'), (b'100G', b'100 Gramos'), (b'1K', b'1 Kg'), (b'10K', b'10 Kg'), (b'25K', b'25 Kg'), (b'1L', b'1 Litro'), (b'5L', b'5 Litros')], default=b'U', error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=20),
        ),
    ]
