# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_auto_20180405_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprabarril',
            name='barril',
        ),
        migrations.RemoveField(
            model_name='comprabarril',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='comprainsumo',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='comprainsumo',
            name='insumo',
        ),
        migrations.DeleteModel(
            name='CompraBarril',
        ),
        migrations.DeleteModel(
            name='CompraInsumo',
        ),
    ]
