# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_auto_20180405_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('cantidad', models.FloatField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('p_unitario', models.FloatField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('subtotal', models.FloatField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('compra', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Compra')),
            ],
        ),
    ]
