# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_auto_20180406_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='Detalle',
            field=models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100, null=True),
        ),
    ]
