# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregados_x_Coccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Agregados', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Agregado')),
            ],
        ),
        migrations.CreateModel(
            name='Agregados_x_Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Agregados', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Agregado')),
            ],
        ),
        migrations.CreateModel(
            name='Coccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=None, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Temp_Maceracion', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Maceracion', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Filtrado', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Lavado', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Coccion', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Temp_Final', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('DF', models.CharField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Litros', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Observaciones', models.TextField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fermentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inicio', models.DateField(default=None, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Fecha_Final', models.DateField(default=None, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Litros', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Observaciones', models.TextField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Fermentador', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Fermentador')),
                ('Lote', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Coccion')),
            ],
        ),
        migrations.CreateModel(
            name='Levadura_x_Coccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Coccion', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Coccion')),
                ('Levadura', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Levadura')),
            ],
        ),
        migrations.CreateModel(
            name='Levadura_x_Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Levadura', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Levadura')),
            ],
        ),
        migrations.CreateModel(
            name='Lupulo_x_Coccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Coccion', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Coccion')),
                ('Lupulo', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Lupulo')),
            ],
        ),
        migrations.CreateModel(
            name='Lupulo_x_Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Lupulo', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Lupulo')),
            ],
        ),
        migrations.CreateModel(
            name='Malta_x_Coccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Coccion', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Coccion')),
                ('Malta', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Malta')),
            ],
        ),
        migrations.CreateModel(
            name='Malta_x_Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Malta', models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Malta')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('Litros', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('DI', models.CharField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('DF', models.CharField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100)),
                ('IBUs', models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100, null=True)),
                ('Color', models.CharField(blank=True, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, max_length=100, null=True)),
                ('Temp_Maceracion', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Maceracion', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Filtrado', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Lavado', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Coccion', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Temp_Final', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
                ('Tiempo_Fermentacion', models.IntegerField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'})),
            ],
        ),
        migrations.AddField(
            model_name='malta_x_receta',
            name='Receta',
            field=models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
        migrations.AddField(
            model_name='lupulo_x_receta',
            name='Receta',
            field=models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
        migrations.AddField(
            model_name='levadura_x_receta',
            name='Receta',
            field=models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
        migrations.AddField(
            model_name='coccion',
            name='Receta',
            field=models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='produccion.Receta'),
        ),
        migrations.AddField(
            model_name='agregados_x_receta',
            name='Receta',
            field=models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
        migrations.AddField(
            model_name='agregados_x_coccion',
            name='Coccion',
            field=models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Coccion'),
        ),
    ]
