# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_agregados_x_receta_estilo_levadura_x_receta_lupulo_x_receta_malta_x_receta_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregados_x_receta',
            name='Agregados',
        ),
    ]
