# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_remove_agregados_x_receta_agregados'),
    ]

    operations = [
    ]
