# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_auto_20171002_1650'),
    ]

    operations = [
    ]
