# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_agregado'),
        ('produccion', '0005_auto_20171012_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregados_x_receta',
            name='Agregados',
            field=models.ForeignKey(default=None, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.Agregado'),
        ),
    ]
