# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_agregados_x_receta_agregados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='Alochol',
            new_name='Alcohol',
        ),
    ]
