# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_auto_20171019_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='Malta',
        ),
        migrations.AddField(
            model_name='receta',
            name='Malta',
            field=models.ManyToManyField(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, to='produccion.Malta_x_Receta'),
        ),
    ]
