# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_auto_20171027_1015'),
    ]

    operations = [
    ]
