# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_auto_20171027_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='Agregado',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='Levadura',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='Lupulo',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='Malta',
        ),
        migrations.AddField(
            model_name='agregados_x_receta',
            name='Receta',
            field=models.ForeignKey(default=None, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
        migrations.AddField(
            model_name='levadura_x_receta',
            name='Receta',
            field=models.ForeignKey(default=None, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
        migrations.AddField(
            model_name='lupulo_x_receta',
            name='Receta',
            field=models.ForeignKey(default=None, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
        migrations.AddField(
            model_name='malta_x_receta',
            name='Receta',
            field=models.ForeignKey(default=None, error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
    ]
