# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_auto_20171027_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregados_x_receta',
            name='Receta',
            field=models.ForeignKey(error_messages={b'invalid': b'Ingrese un valor valido', b'required': b'Este valor es requerido', b'unique': b'Este valor ya fue utilizado'}, on_delete=django.db.models.deletion.CASCADE, to='produccion.Receta'),
        ),
    ]
