# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_auto_20171031_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='DF',
            field=models.CharField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='DI',
            field=models.CharField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100),
        ),
    ]
