# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_auto_20171101_1425'),
    ]

    operations = [
    ]
