# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_auto_20171101_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='id',
            field=models.IntegerField(default='1', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Nombre',
            field=models.CharField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100),
        ),
    ]
