# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0025_remove_receta_tiempo_coccion'),
    ]

    operations = [
    ]
