# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0029_auto_20171102_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='Tiempo_Coccion',
        ),
    ]
