# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0030_remove_receta_tiempo_coccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='Tiempo_Coccion',
            field=models.IntegerField(default='1', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
    ]
