# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0032_auto_20171102_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coccion',
            old_name='Tiempo_Coccion',
            new_name='Tiempo_Hervor',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='Tiempo_Coccion',
            new_name='Tiempo_Hervor',
        ),
        migrations.AddField(
            model_name='coccion',
            name='Nota',
            field=models.TextField(default='0', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100),
        ),
    ]
