# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0034_auto_20171102_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coccion',
            name='Nota',
        ),
    ]
