# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0036_coccion_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregados_x_coccion',
            name='Agregados',
        ),
        migrations.RemoveField(
            model_name='agregados_x_coccion',
            name='Coccion',
        ),
        migrations.RemoveField(
            model_name='coccion',
            name='Receta',
        ),
        migrations.RemoveField(
            model_name='levadura_x_coccion',
            name='Coccion',
        ),
        migrations.RemoveField(
            model_name='levadura_x_coccion',
            name='Levadura',
        ),
        migrations.RemoveField(
            model_name='lupulo_x_coccion',
            name='Coccion',
        ),
        migrations.RemoveField(
            model_name='lupulo_x_coccion',
            name='Lupulo',
        ),
        migrations.RemoveField(
            model_name='malta_x_coccion',
            name='Coccion',
        ),
        migrations.RemoveField(
            model_name='malta_x_coccion',
            name='Malta',
        ),
        migrations.DeleteModel(
            name='Agregados_x_Coccion',
        ),
        migrations.DeleteModel(
            name='Coccion',
        ),
        migrations.DeleteModel(
            name='Levadura_x_Coccion',
        ),
        migrations.DeleteModel(
            name='Lupulo_x_Coccion',
        ),
        migrations.DeleteModel(
            name='Malta_x_Coccion',
        ),
    ]
