# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0037_auto_20171106_0913'),
    ]

    operations = [
    ]
