# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0041_coccion_tiempo_hervor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coccion',
            name='Tiempo_Hervor',
            field=models.IntegerField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
    ]
