# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0044_remove_coccion_tiempo_hervor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coccion',
            name='Tiempo_Hervor',
            field=models.IntegerField(default=None, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
    ]
