# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0045_coccion_tiempo_hervor'),
    ]

    operations = [
    ]
