# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0049_coccion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='coccion',
            name='Fecha',
            field=models.DateField(default=None, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AlterField(
            model_name='coccion',
            name='Nombre',
            field=models.CharField(error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100),
        ),
    ]
