# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0050_auto_20171106_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coccion',
            old_name='Nota',
            new_name='Observaciones',
        ),
        migrations.RemoveField(
            model_name='coccion',
            name='Alcohol',
        ),
        migrations.RemoveField(
            model_name='coccion',
            name='EBC',
        ),
        migrations.RemoveField(
            model_name='coccion',
            name='Eficiencia',
        ),
        migrations.RemoveField(
            model_name='coccion',
            name='IBUs',
        ),
    ]
