# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0052_auto_20171106_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='Eficiencia',
            new_name='Rendimiento',
        ),
    ]
