# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0054_auto_20171130_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coccion',
            name='Tiempo_Filtrado',
            field=models.IntegerField(default='1', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AlterField(
            model_name='coccion',
            name='Tiempo_Lavado',
            field=models.IntegerField(default='1', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Tiempo_Filtrado',
            field=models.IntegerField(default='1', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Tiempo_Lavado',
            field=models.IntegerField(default='1', error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}),
        ),
    ]
