# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0057_auto_20171130_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coccion',
            old_name='Tiempo_Hervor',
            new_name='Tiempo_Coccion',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='Tiempo_Hervor',
            new_name='Tiempo_Coccion',
        ),
    ]
