# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0058_auto_20171130_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='EBC',
            field=models.CharField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='IBUs',
            field=models.CharField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Rendimiento',
            field=models.CharField(blank=True, error_messages={'invalid': 'Ingrese un valor valido', 'required': 'Este valor es requerido', 'unique': 'Este valor ya fue utilizado'}, max_length=100, null=True),
        ),
    ]
